.TH INTERNSCTL 1 "January 2024" "Version 1.0" "internsctl1 
manual"

.SH NAME
internsctl \- Manage interns and related tasks

.SH SYNOPSIS
\fBinternsctl\fP [\fIOPTION\fP]...

.SH DESCRIPTION
The \fBinternsctl\fP command is a tool for managing 
interns and related tasks in your organization. It 
provides functionality for creating, updating, and 
retrieving information about interns.

.SH OPTIONS
.TP
\fB-h, --help\fP
Display help information.

.TP
\fB-v, --version\fP
Display the version number of internsctl1.

.TP
\fB-c, --create\fP
Create a new intern profile.

.TP
\fB-u, --update\fP
Update an exisiting intern's information.

.TP
\fB-r, --retrieve\fP
Retrieve information about interns.

.SH EXAMPLES
Create a new intern profile:
```bash
internsctl -c

internsctl -u vijayant
internsctl - r vijayant

.SH SEE ALSO
\fBman(1)\fP,\fBnano(1)\fP,\fBvim(1)\fP

.SH AUTHOR
vijayant pant 
Contact: vijayantpant@gmail.com

.SH BUGS 
Report bugs to: https:abc.com/bugtracker

.SH COPYRIGHT
Copyright(C) 2024

.SH VERSION
Version 1.0
